// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVWpFoCuSG1cDVlmhl3j0dFskYQwUNKzU',
    appId: '1:45938277026:web:88dbbfa4889695067df5fb',
    messagingSenderId: '45938277026',
    projectId: 'login-app-d5657',
    authDomain: 'login-app-d5657.firebaseapp.com',
    storageBucket: 'login-app-d5657.appspot.com',
    measurementId: 'G-4LPGJC0NHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ezTSma6pzWlJqOzaJxaGdc1TUYrWeeI',
    appId: '1:45938277026:android:495e03f24ab8880d7df5fb',
    messagingSenderId: '45938277026',
    projectId: 'login-app-d5657',
    storageBucket: 'login-app-d5657.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-qCM0tiC2X85a_IDUyjE6VfpD7ivMI4Q',
    appId: '1:45938277026:ios:7ee58edb5e412cdc7df5fb',
    messagingSenderId: '45938277026',
    projectId: 'login-app-d5657',
    storageBucket: 'login-app-d5657.appspot.com',
    iosBundleId: 'com.my_login_',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-qCM0tiC2X85a_IDUyjE6VfpD7ivMI4Q',
    appId: '1:45938277026:ios:7ee58edb5e412cdc7df5fb',
    messagingSenderId: '45938277026',
    projectId: 'login-app-d5657',
    storageBucket: 'login-app-d5657.appspot.com',
    iosBundleId: 'com.my_login_',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVWpFoCuSG1cDVlmhl3j0dFskYQwUNKzU',
    appId: '1:45938277026:web:595cb33f27eec6c97df5fb',
    messagingSenderId: '45938277026',
    projectId: 'login-app-d5657',
    authDomain: 'login-app-d5657.firebaseapp.com',
    storageBucket: 'login-app-d5657.appspot.com',
    measurementId: 'G-8R0EDG61SQ',
  );
}
